### ISSUE TITLE
Mineros should accept host and port via CLI args

### ISSUE THREAD

**Issue by jromero** [EmberCrypto/Blaze#10]
In the event that Meros and Mineros processes are not colocated Mineros should accept a host address and port number for RPC communication. 

The [function](https://github.com/MerosCrypto/Nim-Meros-RPC/blob/60869b02bb101fa327eb2eb38d3fa1abe99ca033/MerosRPC/MerosRPCObj.nim#L49-L52) already appears to support the function and it's only a matter of passing arguments to it.

https://github.com/MerosCrypto/Mineros/blob/a7e498797486a2ab4afa17e4ba6bcc88b310d0ae/src/main.nim#L30

**Comment by kayabaNerve** [comment]
We should be able to easily repurpose Meros's configuration code for this. We should also turn the key into a proper config option, instead of a value appended to the command.

**Comment by jromero** [comment]
Was just about to open a new issue but I'll piggyback on this one for a bit since you brought up the key.

What's the reason a key is necessary? Why doesn't Mineros retrieve it automatically given it's connecting via RCP? What's the value of a user having to manually execute an RCP call to get the key?

**Comment by kayabaNerve** [comment]
I'd like to first note Meros's merit_getBlockTemplate method is bad for a lot of reasons. It should take in a key and output an ID and a header. That's it. I'd like to use the assumption that the merit_getBlockTemplate is defined as that for the rest of this conversation.

Meros shouldn't require that the node has the same key as the template required. Why? Only one Meros node can have a specific miner key at a time. If multiple nodes have the same miner key, they will cause Merit Removals thanks to voting on different transactions and using the same nonces. If you use multiple nodes to provide block templates, say one per location (since you do need a node to generate them), only one can actually have THE miner key.

**Comment by jromero** [comment]
It sounds like you are saying that you should be able to have multiple mining nodes per Meros instance. Is that accurate? If so, how does that play with the key? I would hope that, again, the key could be retrieved by the miner given it was able to connect via RCP. If that is a problem then there is a bigger concern.
